dist: trusty
language: elixir
elixir:
  - 1.3.4
otp_release:
  - 19.0
addons:
  postgresql: "9.6"
services:
  - postgresql
sudo: required
before_script:
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
  - MIX_ENV=test mix spherium.auth.migrate
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - MIX_ENV=test mix deps.compile
  - psql -c "CREATE USER main WITH PASSWORD 'kuz60TOL12' SUPERUSER LOGIN CREATEDB;" -U postgres
script:
  - mix test
notifications:
  recipients:
    - ekuklu@icloud.com
