language: elixir
elixir:
  - 1.3.2
otp_release:
  - 19.0
addons:
  postgresql: "9.4"
services:
  - postgresql
sudo: required
before_script:
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - psql -c 'create user second superuser password kuz60TOL12 login;' -U postgres
script:
  - mix test
notifications:
  recipients:
    - ekuklu@icloud.com
